import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterComponent from "./components/footers/footer.component";
import SideWhatsappIconComponent from "./components/SideWhatsappIcon.component";
import BuyerNavbarComponent from "./components/navbars/BuyerNavbar.component";
import { Suspense } from "react";
import Loading from "./components/Loading.component";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://www.shovexa.com"),

  title: {
    default: "Shovexa",
    template: "%s | Shovexa",
  },

  description:
    "Shovexa is an online shopping marketplace in Pakistan where customers can buy electronics, fashion, home essentials, and more from trusted sellers.",

  keywords: [
  "s",
  "sh",
  "sho",
  "shov",
  "shove",
  "shovex",
  "shovexa",
  "shovexa pakistan",
  "shovexa store",
  "shovexa online",
  "shovexa shop",
  "shovexa collection",
  "shovexa deals",
  "shovexa sale",
  "shovexa official",
  "shovexa reviews",
  "shovexa login",
  "shovexa website",
  "shovexa app",
  "shovexa near me",
  "shovexa cheap",
  "shovexa discount",
  "shovexa coupon code",
  "shovexa promo code",
  "shovexa customer service",
  "shovexa tracking order",
  "shovexa return policy",
  "shovexa sign up",
  "shovexa outlet",
  "shovexa wholesale",
  "shovexa bulk order",
  "shovexa gift card",
  "shovexa loyalty program",
  "shovexa official website",
  "shovexa customer care number",
  "shovexa shopping app",
  "shovexa order tracking",
  "shovexa refund policy",
  "shovexa delivery charges",
  "shovexa new arrivals",
  "shovexa flash sale",
  "shovexa clearance sale",
  "shovexa best sellers",
  "shovexa top products",
  "shovexa official store",
  "shovexa verified store",
  "shovexa trusted seller",
  "shovexa warranty",
  "shovexa size guide",
  "shovexa shipping policy",
  "shovexa exchange policy",
  "shovexa gift vouchers",
  "shovexa membership",
  "shovexa student discount",
  "shovexa first order discount",
  "shovexa black friday sale",
  "shovexa eid sale",
  "shovexa ramadan sale",
  "shovexa winter sale",
  "shovexa summer sale",
  "shovexa electronics",
  "shovexa mobiles",
  "shovexa smartphones",
  "shovexa laptops",
  "shovexa fashion",
  "shovexa men's fashion",
  "shovexa women's fashion",
  "shovexa kids fashion",
  "shovexa home essentials",
  "shovexa kitchen appliances",
  "shovexa home decor",
  "shovexa beauty products",
  "shovexa skincare",
  "shovexa makeup",
  "shovexa shoes",
  "shovexa bags",
  "shovexa watches",
  "shovexa jewelry",
  "shovexa sportswear",
  "shovexa fitness gear",
  "shovexa toys",
  "shovexa books",
  "shovexa stationery",
  "shovexa furniture",
  "shovexa bedding",
  "shovexa curtains",
  "shovexa rugs",
  "shovexa kitchenware",
  "shovexa cookware",
  "shovexa home appliances",
  "shovexa air conditioners",
  "shovexa refrigerators",
  "shovexa washing machines",
  "shovexa televisions",
  "shovexa cameras",
  "shovexa headphones",
  "shovexa earbuds",
  "shovexa smartwatches",
  "shovexa tablets",
  "shovexa gaming accessories",
  "shovexa office supplies",
  "shovexa baby products",
  "shovexa pet supplies",
  "shovexa garden tools",
  "shovexa car accessories",
  "shovexa health supplements",
  "shovexa perfumes",
  "shovexa sunglasses",
  "shovexa handbags",
  "shovexa wallets",
  "shovexa belts",
  "shovexa winter wear",
  "shovexa summer wear",
  "shovexa formal wear",
  "shovexa casual wear",
  "shovexa sneakers",
  "shovexa sandals",
  "shovexa abayas",
  "shovexa kurtis",
  "shovexa lawn suits",
  "shovexa unstitched fabric",
  "shovexa stitched suits",
  "shovexa hijabs",
  "shovexa kids toys",
  "shovexa baby clothes",
  "shovexa home fragrance",
  "shovexa led lights",
  "shovexa power banks",
  "shovexa chargers",
  "shovexa memory cards",
  "shovexa routers",
  "shovexa printers",
  "shovexa office chairs",
  "shovexa study tables",
  "shovexa Karachi",
  "shovexa online shopping Karachi",
  "shovexa Lahore",
  "shovexa online shopping Lahore",
  "shovexa Islamabad",
  "shovexa online shopping Islamabad",
  "shovexa Rawalpindi",
  "shovexa online shopping Rawalpindi",
  "shovexa Faisalabad",
  "shovexa online shopping Faisalabad",
  "shovexa Multan",
  "shovexa online shopping Multan",
  "shovexa Peshawar",
  "shovexa online shopping Peshawar",
  "shovexa Quetta",
  "shovexa online shopping Quetta",
  "shovexa Sialkot",
  "shovexa online shopping Sialkot",
  "shovexa Gujranwala",
  "shovexa online shopping Gujranwala",
  "shovexa Hyderabad",
  "shovexa online shopping Hyderabad",
  "shovexa Bahawalpur",
  "shovexa online shopping Bahawalpur",
  "shovexa Sargodha",
  "shovexa online shopping Sargodha",
  "shovexa Sukkur",
  "shovexa online shopping Sukkur",
  "electronics Pakistan",
  "buy electronics online Pakistan",
  "mobiles Pakistan",
  "buy mobiles online Pakistan",
  "smartphones Pakistan",
  "buy smartphones online Pakistan",
  "laptops Pakistan",
  "buy laptops online Pakistan",
  "fashion Pakistan",
  "buy fashion online Pakistan",
  "men's fashion Pakistan",
  "buy men's fashion online Pakistan",
  "women's fashion Pakistan",
  "buy women's fashion online Pakistan",
  "kids fashion Pakistan",
  "buy kids fashion online Pakistan",
  "home essentials Pakistan",
  "buy home essentials online Pakistan",
  "kitchen appliances Pakistan",
  "buy kitchen appliances online Pakistan",
  "home decor Pakistan",
  "buy home decor online Pakistan",
  "beauty products Pakistan",
  "buy beauty products online Pakistan",
  "skincare Pakistan",
  "buy skincare online Pakistan",
  "makeup Pakistan",
  "buy makeup online Pakistan",
  "shoes Pakistan",
  "buy shoes online Pakistan",
  "bags Pakistan",
  "buy bags online Pakistan",
  "watches Pakistan",
  "buy watches online Pakistan",
  "jewelry Pakistan",
  "buy jewelry online Pakistan",
  "sportswear Pakistan",
  "buy sportswear online Pakistan",
  "fitness gear Pakistan",
  "buy fitness gear online Pakistan",
  "toys Pakistan",
  "buy toys online Pakistan",
  "books Pakistan",
  "buy books online Pakistan",
  "stationery Pakistan",
  "buy stationery online Pakistan",
  "furniture Pakistan",
  "buy furniture online Pakistan",
  "bedding Pakistan",
  "buy bedding online Pakistan",
  "curtains Pakistan",
  "buy curtains online Pakistan",
  "rugs Pakistan",
  "buy rugs online Pakistan",
  "kitchenware Pakistan",
  "buy kitchenware online Pakistan",
  "cookware Pakistan",
  "buy cookware online Pakistan",
  "home appliances Pakistan",
  "buy home appliances online Pakistan",
  "air conditioners Pakistan",
  "buy air conditioners online Pakistan",
  "refrigerators Pakistan",
  "buy refrigerators online Pakistan",
  "washing machines Pakistan",
  "buy washing machines online Pakistan",
  "televisions Pakistan",
  "buy televisions online Pakistan",
  "cameras Pakistan",
  "buy cameras online Pakistan",
  "headphones Pakistan",
  "buy headphones online Pakistan",
  "earbuds Pakistan",
  "buy earbuds online Pakistan",
  "smartwatches Pakistan",
  "buy smartwatches online Pakistan",
  "tablets Pakistan",
  "buy tablets online Pakistan",
  "gaming accessories Pakistan",
  "buy gaming accessories online Pakistan",
  "office supplies Pakistan",
  "buy office supplies online Pakistan",
  "baby products Pakistan",
  "buy baby products online Pakistan",
  "pet supplies Pakistan",
  "buy pet supplies online Pakistan",
  "garden tools Pakistan",
  "buy garden tools online Pakistan",
  "car accessories Pakistan",
  "buy car accessories online Pakistan",
  "health supplements Pakistan",
  "buy health supplements online Pakistan",
  "perfumes Pakistan",
  "buy perfumes online Pakistan",
  "sunglasses Pakistan",
  "buy sunglasses online Pakistan",
  "handbags Pakistan",
  "buy handbags online Pakistan",
  "wallets Pakistan",
  "buy wallets online Pakistan",
  "belts Pakistan",
  "buy belts online Pakistan",
  "winter wear Pakistan",
  "buy winter wear online Pakistan",
  "summer wear Pakistan",
  "buy summer wear online Pakistan",
  "formal wear Pakistan",
  "buy formal wear online Pakistan",
  "casual wear Pakistan",
  "buy casual wear online Pakistan",
  "sneakers Pakistan",
  "buy sneakers online Pakistan",
  "sandals Pakistan",
  "buy sandals online Pakistan",
  "abayas Pakistan",
  "buy abayas online Pakistan",
  "kurtis Pakistan",
  "buy kurtis online Pakistan",
  "lawn suits Pakistan",
  "buy lawn suits online Pakistan",
  "unstitched fabric Pakistan",
  "buy unstitched fabric online Pakistan",
  "stitched suits Pakistan",
  "buy stitched suits online Pakistan",
  "hijabs Pakistan",
  "buy hijabs online Pakistan",
  "kids toys Pakistan",
  "buy kids toys online Pakistan",
  "baby clothes Pakistan",
  "buy baby clothes online Pakistan",
  "home fragrance Pakistan",
  "buy home fragrance online Pakistan",
  "led lights Pakistan",
  "buy led lights online Pakistan",
  "power banks Pakistan",
  "buy power banks online Pakistan",
  "chargers Pakistan",
  "buy chargers online Pakistan",
  "memory cards Pakistan",
  "buy memory cards online Pakistan",
  "routers Pakistan",
  "buy routers online Pakistan",
  "printers Pakistan",
  "buy printers online Pakistan",
  "office chairs Pakistan",
  "buy office chairs online Pakistan",
  "study tables Pakistan",
  "buy study tables online Pakistan",
  "electronics Karachi",
  "electronics Lahore",
  "electronics Islamabad",
  "electronics Rawalpindi",
  "mobiles Karachi",
  "mobiles Lahore",
  "mobiles Islamabad",
  "mobiles Rawalpindi",
  "smartphones Karachi",
  "smartphones Lahore",
  "smartphones Islamabad",
  "smartphones Rawalpindi",
  "laptops Karachi",
  "laptops Lahore",
  "laptops Islamabad",
  "laptops Rawalpindi",
  "fashion Karachi",
  "fashion Lahore",
  "fashion Islamabad",
  "fashion Rawalpindi",
  "men's fashion Karachi",
  "men's fashion Lahore",
  "men's fashion Islamabad",
  "men's fashion Rawalpindi",
  "women's fashion Karachi",
  "women's fashion Lahore",
  "women's fashion Islamabad",
  "women's fashion Rawalpindi",
  "kids fashion Karachi",
  "kids fashion Lahore",
  "kids fashion Islamabad",
  "kids fashion Rawalpindi",
  "home essentials Karachi",
  "home essentials Lahore",
  "home essentials Islamabad",
  "home essentials Rawalpindi",
  "kitchen appliances Karachi",
  "kitchen appliances Lahore",
  "kitchen appliances Islamabad",
  "kitchen appliances Rawalpindi",
  "home decor Karachi",
  "home decor Lahore",
  "home decor Islamabad",
  "home decor Rawalpindi",
  "beauty products Karachi",
  "beauty products Lahore",
  "beauty products Islamabad",
  "beauty products Rawalpindi",
  "skincare Karachi",
  "skincare Lahore",
  "skincare Islamabad",
  "skincare Rawalpindi",
  "makeup Karachi",
  "makeup Lahore",
  "makeup Islamabad",
  "makeup Rawalpindi",
  "shoes Karachi",
  "shoes Lahore",
  "shoes Islamabad",
  "shoes Rawalpindi",
  "bags Karachi",
  "bags Lahore",
  "bags Islamabad",
  "bags Rawalpindi",
  "watches Karachi",
  "watches Lahore",
  "watches Islamabad",
  "watches Rawalpindi",
  "jewelry Karachi",
  "jewelry Lahore",
  "jewelry Islamabad",
  "jewelry Rawalpindi",
  "sportswear Karachi",
  "sportswear Lahore",
  "sportswear Islamabad",
  "sportswear Rawalpindi",
  "fitness gear Karachi",
  "fitness gear Lahore",
  "fitness gear Islamabad",
  "fitness gear Rawalpindi",
  "toys Karachi",
  "toys Lahore",
  "toys Islamabad",
  "toys Rawalpindi",
  "books Karachi",
  "books Lahore",
  "books Islamabad",
  "books Rawalpindi",
  "stationery Karachi",
  "stationery Lahore",
  "stationery Islamabad",
  "stationery Rawalpindi",
  "furniture Karachi",
  "furniture Lahore",
  "furniture Islamabad",
  "furniture Rawalpindi",
  "bedding Karachi",
  "bedding Lahore",
  "bedding Islamabad",
  "bedding Rawalpindi",
  "curtains Karachi",
  "curtains Lahore",
  "curtains Islamabad",
  "curtains Rawalpindi",
  "rugs Karachi",
  "rugs Lahore",
  "rugs Islamabad",
  "rugs Rawalpindi",
  "kitchenware Karachi",
  "kitchenware Lahore",
  "kitchenware Islamabad",
  "kitchenware Rawalpindi",
  "cookware Karachi",
  "cookware Lahore",
  "cookware Islamabad",
  "cookware Rawalpindi",
  "home appliances Karachi",
  "home appliances Lahore",
  "home appliances Islamabad",
  "home appliances Rawalpindi",
  "online shopping Pakistan",
  "Pakistan ecommerce",
  "best online shopping site Pakistan",
  "cheap online shopping Pakistan",
  "online shopping app Pakistan",
  "buy online Pakistan",
  "free delivery Pakistan",
  "cash on delivery Pakistan",
  "online marketplace Pakistan",
  "trusted online store Pakistan",
  "fast delivery online shopping",
  "secure online payment Pakistan",
  "online deals Pakistan",
  "daily deals Pakistan",
  "flash sale Pakistan",
  "clearance sale Pakistan",
  "new arrivals Pakistan",
  "top rated online store",
  "24/7 customer support online shopping",
  "easy returns online shopping",
  "affordable online shopping Pakistan",
  "shop now pay later Pakistan",
  "installment shopping Pakistan",
  "EMI shopping Pakistan",
  "discounted products Pakistan",
  "seasonal sale Pakistan",
  "festival sale Pakistan",
  "gift ideas online Pakistan",
  "home delivery shopping Pakistan",
  "mobile shopping app",
  "shopping cart online",
  "wishlist online shopping",
  "product reviews online store",
  "verified online store Pakistan",
  "authentic products Pakistan",
  "genuine products online",
  "online shopping deals today",
  "best deals of the day",
  "top online stores 2026",
  "ecommerce trends Pakistan",
  "digital shopping Pakistan",
  "shovexa.com",
  "shovexa.pk",
  "shovexa clothing",
  "shovexa home",
  "shovexa kitchen",
  "shovexa beauty",
  "shovexa kids",
  "shovexa men",
  "shovexa women",
  "shovexa sale 2026",
  "shovexa discount code",
  "shovexa promo 2026",
  "shovexa reviews Pakistan",
  "electronics shopping Karachi",
  "electronics shopping Lahore",
  "electronics shopping Islamabad",
  "electronics shopping Rawalpindi",
  "electronics shopping Faisalabad",
  "electronics shopping Multan",
  "electronics shopping Peshawar",
  "electronics shopping Quetta",
  "electronics shopping Sialkot",
  "electronics shopping Gujranwala",
  "electronics shopping Hyderabad",
  "electronics shopping Bahawalpur",
  "electronics shopping Sargodha",
  "electronics shopping Sukkur",
  "mobiles shopping Karachi",
  "mobiles shopping Lahore",
  "mobiles shopping Islamabad",
  "mobiles shopping Rawalpindi",
  "mobiles shopping Faisalabad",
  "mobiles shopping Multan",
  "mobiles shopping Peshawar",
  "mobiles shopping Quetta",
  "mobiles shopping Sialkot",
  "mobiles shopping Gujranwala",
  "mobiles shopping Hyderabad",
  "mobiles shopping Bahawalpur",
  "mobiles shopping Sargodha",
  "mobiles shopping Sukkur",
  "smartphones shopping Karachi",
  "smartphones shopping Lahore",
  "smartphones shopping Islamabad",
  "smartphones shopping Rawalpindi",
  "smartphones shopping Faisalabad",
  "smartphones shopping Multan",
  "smartphones shopping Peshawar",
  "smartphones shopping Quetta",
  "smartphones shopping Sialkot",
  "smartphones shopping Gujranwala",
  "smartphones shopping Hyderabad",
  "smartphones shopping Bahawalpur",
  "smartphones shopping Sargodha",
  "smartphones shopping Sukkur",
  "laptops shopping Karachi",
  "laptops shopping Lahore",
  "laptops shopping Islamabad",
  "laptops shopping Rawalpindi",
  "laptops shopping Faisalabad",
  "laptops shopping Multan",
  "laptops shopping Peshawar",
  "laptops shopping Quetta",
  "laptops shopping Sialkot",
  "laptops shopping Gujranwala",
  "laptops shopping Hyderabad",
  "laptops shopping Bahawalpur",
  "laptops shopping Sargodha",
  "laptops shopping Sukkur",
  "fashion shopping Karachi",
  "fashion shopping Lahore",
  "fashion shopping Islamabad",
  "fashion shopping Rawalpindi",
  "fashion shopping Faisalabad",
  "fashion shopping Multan",
  "fashion shopping Peshawar",
  "fashion shopping Quetta",
  "fashion shopping Sialkot",
  "fashion shopping Gujranwala",
  "fashion shopping Hyderabad",
  "fashion shopping Bahawalpur",
  "fashion shopping Sargodha",
  "fashion shopping Sukkur",
  "men's fashion shopping Karachi",
  "men's fashion shopping Lahore",
  "men's fashion shopping Islamabad",
  "men's fashion shopping Rawalpindi",
  "men's fashion shopping Faisalabad",
  "men's fashion shopping Multan",
  "men's fashion shopping Peshawar",
  "men's fashion shopping Quetta",
  "men's fashion shopping Sialkot",
  "men's fashion shopping Gujranwala",
  "men's fashion shopping Hyderabad",
  "men's fashion shopping Bahawalpur",
  "men's fashion shopping Sargodha",
  "men's fashion shopping Sukkur",
  "women's fashion shopping Karachi",
  "women's fashion shopping Lahore",
  "women's fashion shopping Islamabad",
  "women's fashion shopping Rawalpindi",
  "women's fashion shopping Faisalabad",
  "women's fashion shopping Multan",
  "women's fashion shopping Peshawar",
  "women's fashion shopping Quetta",
  "women's fashion shopping Sialkot",
  "women's fashion shopping Gujranwala",
  "women's fashion shopping Hyderabad",
  "women's fashion shopping Bahawalpur",
  "women's fashion shopping Sargodha",
  "women's fashion shopping Sukkur",
  "kids fashion shopping Karachi",
  "kids fashion shopping Lahore",
  "kids fashion shopping Islamabad",
  "kids fashion shopping Rawalpindi",
  "kids fashion shopping Faisalabad",
  "kids fashion shopping Multan",
  "kids fashion shopping Peshawar",
  "kids fashion shopping Quetta",
  "kids fashion shopping Sialkot",
  "kids fashion shopping Gujranwala",
  "kids fashion shopping Hyderabad",
  "kids fashion shopping Bahawalpur",
  "kids fashion shopping Sargodha",
  "kids fashion shopping Sukkur",
  "home essentials shopping Karachi",
  "home essentials shopping Lahore",
  "home essentials shopping Islamabad",
  "home essentials shopping Rawalpindi",
  "home essentials shopping Faisalabad",
  "home essentials shopping Multan",
  "home essentials shopping Peshawar",
  "home essentials shopping Quetta",
  "home essentials shopping Sialkot",
  "home essentials shopping Gujranwala",
  "home essentials shopping Hyderabad",
  "home essentials shopping Bahawalpur",
  "home essentials shopping Sargodha",
  "home essentials shopping Sukkur",
  "kitchen appliances shopping Karachi",
  "kitchen appliances shopping Lahore",
  "kitchen appliances shopping Islamabad",
  "kitchen appliances shopping Rawalpindi",
  "kitchen appliances shopping Faisalabad",
  "kitchen appliances shopping Multan",
  "kitchen appliances shopping Peshawar",
  "kitchen appliances shopping Quetta",
  "kitchen appliances shopping Sialkot",
  "kitchen appliances shopping Gujranwala",
  "kitchen appliances shopping Hyderabad",
  "kitchen appliances shopping Bahawalpur",
  "kitchen appliances shopping Sargodha",
  "kitchen appliances shopping Sukkur",
  "home decor shopping Karachi",
  "home decor shopping Lahore",
  "home decor shopping Islamabad",
  "home decor shopping Rawalpindi",
  "home decor shopping Faisalabad",
  "home decor shopping Multan",
  "home decor shopping Peshawar",
  "home decor shopping Quetta",
  "home decor shopping Sialkot",
  "home decor shopping Gujranwala",
  "home decor shopping Hyderabad",
  "home decor shopping Bahawalpur",
  "home decor shopping Sargodha",
  "home decor shopping Sukkur",
  "beauty products shopping Karachi",
  "beauty products shopping Lahore",
  "beauty products shopping Islamabad",
  "beauty products shopping Rawalpindi",
  "beauty products shopping Faisalabad",
  "beauty products shopping Multan",
  "beauty products shopping Peshawar",
  "beauty products shopping Quetta",
  "beauty products shopping Sialkot",
  "beauty products shopping Gujranwala",
  "beauty products shopping Hyderabad",
  "beauty products shopping Bahawalpur",
  "beauty products shopping Sargodha",
  "beauty products shopping Sukkur",
  "skincare shopping Karachi",
  "skincare shopping Lahore",
  "skincare shopping Islamabad",
  "skincare shopping Rawalpindi",
  "skincare shopping Faisalabad",
  "skincare shopping Multan",
  "skincare shopping Peshawar",
  "skincare shopping Quetta",
  "skincare shopping Sialkot",
  "skincare shopping Gujranwala",
  "skincare shopping Hyderabad",
  "skincare shopping Bahawalpur",
  "skincare shopping Sargodha",
  "skincare shopping Sukkur",
  "makeup shopping Karachi",
  "makeup shopping Lahore",
  "makeup shopping Islamabad",
  "makeup shopping Rawalpindi",
  "makeup shopping Faisalabad",
  "makeup shopping Multan",
  "makeup shopping Peshawar",
  "makeup shopping Quetta",
  "makeup shopping Sialkot",
  "makeup shopping Gujranwala",
  "makeup shopping Hyderabad",
  "makeup shopping Bahawalpur",
  "makeup shopping Sargodha",
  "makeup shopping Sukkur",
  "shoes shopping Karachi",
  "shoes shopping Lahore",
  "earbuds shopping Islamabad",
  "earbuds shopping Rawalpindi",
  "earbuds shopping Faisalabad",
  "earbuds shopping Multan",
  "earbuds shopping Peshawar",
  "earbuds shopping Quetta",
  "earbuds shopping Sialkot",
  "earbuds shopping Gujranwala",
  "earbuds shopping Hyderabad",
  "earbuds shopping Bahawalpur",
    ],

  alternates: {
    canonical: "/",
  },

  openGraph: {
    type: "website",
    url: "https://www.shovexa.com",
    siteName: "Shovexa",
    title: "Shovexa",
    description:
      "Shop electronics, fashion, home essentials, and more from trusted sellers.",
  },

  twitter: {
    card: "summary_large_image",
    title: "Shovexa",
    description:
      "Shop electronics, fashion, home essentials, and more from trusted sellers.",
  },

  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<Loading />}>
          <div className="flex flex-col justify-between  h-auto min-h-screen">
            <div className="relative">
              <BuyerNavbarComponent />
              <div className="fixed bottom-4 right-4 z-50">
                <SideWhatsappIconComponent />
              </div>
            </div>
            <main className="flex-grow">
              {children}
            </main>
            <div >

              <FooterComponent />
            </div>
          </div>
        </Suspense>
      </body>
    </html>
  )
}
